version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  server:
    image: myserver
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:3000
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/mydb?authSource=admin
      CLIENT_URI: http://localhost:8080
  client:
    image: myapp:latest
    restart: always
    ports:
      - 8080:80
    environment:
      VITE_API_URL: http://localhost:8081
    depends_on:
      - server
volumes:
  mongo-data:
    driver: local