version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: todo-app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"  
    volumes:
      - mongo-data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-app
    restart: always
    ports:
      - "3000:3000"  
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongodb:27017/todo-app?authSource=admin
      CLIENT_URI: http://localhost:8080
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: always
    ports:
      - "8080:80"  
    environment:
      VITE_API_URL: http://localhost:3000/api
    depends_on:
      - server

volumes:
  mongo-data:
    driver: local
